import { u as uPub } from "@composehq/ts-public";
import { AppHandler } from "./constants";

interface RequiredAppOptions<TState> {
  /**
   * The name of the app. Used to identify the app in the UI, and as the title of the browser tab.
   *
   * @example "User Management App"
   */
  name: string;
  /**
   * The handler function for the app.
   */
  handler: AppHandler<TState>;
}

interface OptionalAppOptions<TState> {
  /**
   * A unique route to assign to the app and use as the URL slug.
   *
   * If not provided, the route will be auto-generated based on the app name.
   *
   * @correct "user-management-app"
   * @correct "/user-management-app"
   * @incorrect "users/management-app"
   * @incorrect "/user$management$app"
   */
  route: string | null;
  /**
   * A short description of the app to display on the home page.
   */
  description: string | null;
  /**
   * Whether the app should be hidden from the home page.
   */
  hidden?: boolean;
  /**
   * The initial state of the app.
   */
  initialState: TState;
  /**
   * If this app is a sub-page of a multi-page app, declare the parent app
   * route here. Declaring this value will:
   *
   * a) allow this app to inherit permissions from the parent app (e.g. if the
   * parent app is shared with an external email, this app will be too).
   *
   * b) hide this app in the Compose dashboard so that the dashboard isn't
   * cluttered with sub-pages for a multi-page app. This app will still
   * be available programmatically (e.g. via the `page.link` function) and
   * via the URL. This feature can be overriden by directly setting the
   * `hidden` property to `false`.
   */
  parentAppRoute?: string;
}

type AppOptions<TState> = RequiredAppOptions<TState> &
  Partial<OptionalAppOptions<TState>>;

class AppDefinition<TState = Record<string, any>> {
  private name: RequiredAppOptions<TState>["name"];
  handler: RequiredAppOptions<TState>["handler"];
  private description: OptionalAppOptions<TState>["description"];
  private hidden: OptionalAppOptions<TState>["hidden"];
  private _parentAppRoute?: OptionalAppOptions<TState>["parentAppRoute"];

  private _initialState: TState;

  private _isAutoGeneratedRoute: boolean;

  private _route: NonNullable<OptionalAppOptions<TState>["route"]>;

  /**
   * Create a new Compose app.
   *
   * See the {@link AppOptions} interface for more information.
   */
  constructor(options: AppOptions<TState>) {
    this.name = options.name;
    this.handler = options.handler;

    this.description = options.description ?? null;
    this.hidden = options.hidden;
    this._parentAppRoute = options.parentAppRoute
      ? uPub.appRoute.format(options.parentAppRoute)
      : undefined;

    this._initialState = options.initialState ?? ({} as TState);

    this._isAutoGeneratedRoute = !options.route;

    this._route =
      options.route === undefined || options.route === null
        ? uPub.appRoute.addAutoGenerationSuffix(uPub.appRoute.format(this.name))
        : uPub.appRoute.format(options.route);

    try {
      uPub.appRoute.isValid(this._route);
    } catch (error) {
      throw new Error("Invalid route: " + (error as Error).message);
    }

    this.setRoute = this.setRoute.bind(this);
    this.summarize = this.summarize.bind(this);
  }

  setRoute(
    route: NonNullable<AppOptions<TState>["route"]>,
    isAutoGenerated: boolean
  ) {
    this._route = route;
    this._isAutoGeneratedRoute = isAutoGenerated;
  }

  get route() {
    return this._route;
  }

  get parentAppRoute() {
    return this._parentAppRoute;
  }

  summarize() {
    return {
      name: this.name,
      route: this.route,
      description: this.description,
      hidden: this.hidden,
      parentAppRoute: this._parentAppRoute,
    };
  }

  get isAutoGeneratedRoute() {
    return this._isAutoGeneratedRoute;
  }

  get initialState() {
    return this._initialState;
  }
}

export { AppDefinition };
