import { describe, it, expect } from "vitest";
import { AppDefinition } from "./appDefinition";

describe("AppDefinition route handling", () => {
  const dummyHandler = () => {};

  describe("auto-generated routes", () => {
    it("should auto-generate route from app name when no route provided", () => {
      const app = new AppDefinition({
        name: "Test App",
        handler: dummyHandler,
      });

      expect(app.route).toBe("test-app-auto-suffix");
      expect(app.isAutoGeneratedRoute).toBe(true);
    });
  });

  describe("user-provided routes", () => {
    it("should handle multiple spaces in route", () => {
      const app = new AppDefinition({
        name: "Test App",
        handler: dummyHandler,
        route: "test    multiple    spaces",
      });

      expect(app.route).toBe("test----multiple----spaces");
    });

    it("should throw error for empty route", () => {
      expect(() => {
        new AppDefinition({
          name: "Test App",
          handler: dummyHandler,
          route: "",
        });
      }).toThrow("Invalid route");
    });

    it("should accept route with only numbers", () => {
      const app = new AppDefinition({
        name: "Test App",
        handler: dummyHandler,
        route: "123456",
      });

      expect(app.route).toBe("123456");
    });

    it("should accept valid lowercase route", () => {
      const app = new AppDefinition({
        name: "Test App",
        handler: dummyHandler,
        route: "my-test-route",
      });

      expect(app.route).toBe("my-test-route");
      expect(app.isAutoGeneratedRoute).toBe(false);
    });

    it("should convert uppercase route to lowercase", () => {
      const app = new AppDefinition({
        name: "Test App",
        handler: dummyHandler,
        route: "MY-TEST-ROUTE",
      });

      expect(app.route).toBe("my-test-route");
    });

    it("should strip leading forward slashes", () => {
      const app = new AppDefinition({
        name: "Test App",
        handler: dummyHandler,
        route: "/test-route",
      });

      expect(app.route).toBe("test-route");
    });

    it("should strip multiple leading forward slashes", () => {
      const app = new AppDefinition({
        name: "Test App",
        handler: dummyHandler,
        route: "///test-route",
      });

      expect(app.route).toBe("test-route");
    });

    it("should throw error for route with invalid characters", () => {
      expect(() => {
        new AppDefinition({
          name: "Test App",
          handler: dummyHandler,
          route: "test@route",
        });
      }).toThrow("Invalid route");

      expect(() => {
        new AppDefinition({
          name: "Test App",
          handler: dummyHandler,
          route: "test$route",
        });
      }).toThrow("Invalid route");
    });

    it("should handle route with spaces", () => {
      const app = new AppDefinition({
        name: "Test App",
        handler: dummyHandler,
        route: "test route",
      });

      expect(app.route).toBe("test-route");
    });

    it("should throw error for route starting with hyphen", () => {
      expect(() => {
        new AppDefinition({
          name: "Test App",
          handler: dummyHandler,
          route: "-test-route",
        });
      }).toThrow("Invalid route");
    });

    it("should throw error for route ending with hyphen", () => {
      expect(() => {
        new AppDefinition({
          name: "Test App",
          handler: dummyHandler,
          route: "test-route-",
        });
      }).toThrow("Invalid route");
    });

    it("should throw error for route with nested paths", () => {
      expect(() => {
        new AppDefinition({
          name: "Test App",
          handler: dummyHandler,
          route: "test/route",
        });
      }).toThrow("Invalid route");
    });
  });
});
