BEGIN;

    ALTER TABLE "company" ALTER COLUMN "plan" DROP DEFAULT;
    ALTER TABLE "company" ALTER COLUMN "billingId" DROP DEFAULT;
    ALTER TABLE "company" ALTER COLUMN "flags" DROP DEFAULT;

COMMIT;