const LANGUAGE = {
  ADA: "ada",
  CLOJURE: "clojure",
  COFFEESCRIPT: "coffeescript",
  DART: "dart",
  DJANGO: "django",
  DOCKERFILE: "dockerfile",
  DUST: "dust",
  ELIXIR: "elixir",
  ELM: "elm",
  ERLANG: "erlang",
  GRAPHQL: "graphql",
  HASKELL: "haskell",
  JAVA: "java",
  JAVASCRIPT: "javascript",
  JULIA: "julia",
  KOTLIN: "kotlin",
  PYTHON: "python",
  TYPESCRIPT: "typescript",
  JSON: "json",
  HTML: "html",
  CSS: "css",
  SCSS: "scss",
  REACT: "jsx",
  BASH: "bash",
  C: "c",
  "C++": "c++",
  CSHARP: "csharp",
  GO: "go",
  MARKDOWN: "markdown",
  PHP: "php",
  RUBY: "ruby",
  RUST: "rust",
  SQL: "sql",
  SWIFT: "swift",
  XML: "xml",
  YAML: "yaml",
  ZIG: "zig",
  R: "r",
} as const;

type Language = (typeof LANGUAGE)[keyof typeof LANGUAGE];

const LANGUAGE_TO_HLJS_CLASSNAME: { [key in Language]: string } = {
  ada: "language-ada",
  clojure: "language-clojure",
  coffeescript: "language-coffeescript",
  dart: "language-dart",
  django: "language-django",
  dockerfile: "language-dockerfile",
  dust: "language-dust",
  elixir: "language-elixir",
  elm: "language-elm",
  erlang: "language-erlang",
  graphql: "language-graphql",
  haskell: "language-haskell",
  java: "language-java",
  javascript: "language-javascript",
  julia: "language-julia",
  kotlin: "language-kotlin",
  python: "language-python",
  typescript: "language-typescript",
  json: "language-json",
  html: "language-html",
  css: "language-css",
  scss: "language-scss",
  jsx: "language-jsx",
  bash: "language-bash",
  c: "language-c",
  "c++": "language-cpp",
  csharp: "language-csharp",
  go: "language-go",
  markdown: "language-markdown",
  php: "language-php",
  ruby: "language-ruby",
  rust: "language-rust",
  sql: "language-sql",
  swift: "language-swift",
  xml: "language-xml",
  yaml: "language-yaml",
  zig: "language-zig",
  r: "language-r",
};

export {
  LANGUAGE as NAME,
  type Language as LanguageName,
  LANGUAGE_TO_HLJS_CLASSNAME as NAME_TO_HLJS_CLASSNAME,
};
