const ANALYTICS_EVENT = {
  COMPANY_CREATED: "COMPANY_CREATED",
  USER_CREATED: "USER_CREATED",
  APP_INITIALIZED: "APP_INITIALIZED",
  INTERACTIVE_ONBOARDING_STEP: "INTERACTIVE_ONBOARDING_STEP",
  INTERACTIVE_ONBOARDING_SKIPPED: "INTERACTIVE_ONBOARDING_SKIPPED",
  INTERACTIVE_ONBOARDING_CLICKED_REPORT_ISSUE:
    "INTERACTIVE_ONBOARDING_CLICKED_REPORT_ISSUE",
  INTERACTIVE_ONBOARDING_SUBMITTED_ISSUE_REPORT:
    "INTERACTIVE_ONBOARDING_SUBMITTED_ISSUE_REPORT",
} as const;

type AnalyticsEvent = (typeof ANALYTICS_EVENT)[keyof typeof ANALYTICS_EVENT];

export { ANALYTICS_EVENT, AnalyticsEvent };
