const ANALYTICS_EVENT = {
  COMPANY_CREATED: "COMPANY_CREATED",
  USER_CREATED: "USER_CREATED",
  APP_INITIALIZED: "APP_INITIALIZED",
  DASHBOARD_PAGE_VIEW: "DASHBOARD_PAGE_VIEW",
  ONBOARDING_SKIPPED: "ONBOARDING_SKIPPED",
  ONBOARDING_CLICKED_REPORT_ISSUE: "ONBOARDING_CLICKED_REPORT_ISSUE",
  ONBOARDING_SUBMITTED_ISSUE_REPORT: "ONBOARDING_SUBMITTED_ISSUE_REPORT",
  REPORT_CREATED: "REPORT_CREATED",
  REPORT_UPDATED: "REPORT_UPDATED",
  REPORT_DELETED: "REPORT_DELETED",
  REPORT_SHARED: "REPORT_SHARED",
  REPORT_UNSHARED: "REPORT_UNSHARED",
} as const;

type AnalyticsEvent = (typeof ANALYTICS_EVENT)[keyof typeof ANALYTICS_EVENT];

export { ANALYTICS_EVENT, AnalyticsEvent };
