const CONNECTION_HEALTH = {
  GOOD: "good",
  BAD: "bad",
  LOADING: "loading",
} as const;

type ConnectionHealth =
  (typeof CONNECTION_HEALTH)[keyof typeof CONNECTION_HEALTH];

const CONNECTION_STATUS = {
  BROWSER_OFFLINE: "BROWSER_OFFLINE",
  BROWSER_CONNECTING: "BROWSER_CONNECTING",
  BROWSER_RECONNECTING: "BROWSER_RECONNECTING",
  ENVIRONMENT_OFFLINE: "ENVIRONMENT_OFFLINE",
  ENVIRONMENT_CONNECTING: "ENVIRONMENT_CONNECTING",
  ENVIRONMENT_RECONNECTING: "ENVIRONMENT_RECONNECTING",
  SERVER_UPDATE_IN_PROGRESS: "SERVER_UPDATE_IN_PROGRESS",
  ONLINE: "ONLINE",
} as const;

type ConnectionStatus =
  (typeof CONNECTION_STATUS)[keyof typeof CONNECTION_STATUS];

const CONNECTION_STATUS_TO_HEALTH: Record<ConnectionStatus, ConnectionHealth> =
  {
    [CONNECTION_STATUS.BROWSER_OFFLINE]: CONNECTION_HEALTH.BAD,
    [CONNECTION_STATUS.BROWSER_CONNECTING]: CONNECTION_HEALTH.LOADING,
    [CONNECTION_STATUS.BROWSER_RECONNECTING]: CONNECTION_HEALTH.LOADING,
    [CONNECTION_STATUS.ENVIRONMENT_OFFLINE]: CONNECTION_HEALTH.BAD,
    [CONNECTION_STATUS.ENVIRONMENT_CONNECTING]: CONNECTION_HEALTH.LOADING,
    [CONNECTION_STATUS.ENVIRONMENT_RECONNECTING]: CONNECTION_HEALTH.LOADING,
    [CONNECTION_STATUS.SERVER_UPDATE_IN_PROGRESS]: CONNECTION_HEALTH.LOADING,
    [CONNECTION_STATUS.ONLINE]: CONNECTION_HEALTH.GOOD,
  };

const CONNECTION_STATUS_TO_LABEL: Record<ConnectionStatus, string> = {
  [CONNECTION_STATUS.SERVER_UPDATE_IN_PROGRESS]: "Server updating",
  [CONNECTION_STATUS.BROWSER_OFFLINE]: "Browser is offline",
  [CONNECTION_STATUS.BROWSER_CONNECTING]: "Connecting",
  [CONNECTION_STATUS.BROWSER_RECONNECTING]: "Reconnecting",
  [CONNECTION_STATUS.ENVIRONMENT_OFFLINE]: "Offline",
  [CONNECTION_STATUS.ENVIRONMENT_CONNECTING]: "Connecting",
  [CONNECTION_STATUS.ENVIRONMENT_RECONNECTING]: "Reconnecting",
  [CONNECTION_STATUS.ONLINE]: "Online",
};

const CONNECTION_STATUS_TO_SHORT_LABEL: Record<ConnectionStatus, string> = {
  [CONNECTION_STATUS.SERVER_UPDATE_IN_PROGRESS]: "Server updating",
  [CONNECTION_STATUS.BROWSER_OFFLINE]: "Offline",
  [CONNECTION_STATUS.BROWSER_CONNECTING]: "Connecting",
  [CONNECTION_STATUS.BROWSER_RECONNECTING]: "Reconnecting",
  [CONNECTION_STATUS.ENVIRONMENT_OFFLINE]: "Offline",
  [CONNECTION_STATUS.ENVIRONMENT_CONNECTING]: "Connecting",
  [CONNECTION_STATUS.ENVIRONMENT_RECONNECTING]: "Reconnecting",
  [CONNECTION_STATUS.ONLINE]: "Online",
};

// If browser or environment is offline, we'll show a connecting status
// for 10 seconds before showing the offline status.
const CONNECTING_INTERVAL_MS = 15 * 1000;
const RECONNECTING_INTERVAL_MS = 15 * 1000;
const SERVER_UPDATE_GRACE_PERIOD_MS = 25 * 1000;

export {
  CONNECTION_HEALTH,
  CONNECTION_STATUS,
  CONNECTION_STATUS_TO_HEALTH,
  CONNECTION_STATUS_TO_LABEL,
  CONNECTION_STATUS_TO_SHORT_LABEL,
  CONNECTING_INTERVAL_MS,
  RECONNECTING_INTERVAL_MS,
  SERVER_UPDATE_GRACE_PERIOD_MS,
  type ConnectionStatus,
  type ConnectionHealth,
};
