import { useConnectionStatus } from "./useConnectionStatus";
import {
  CONNECTION_HEALTH,
  CONNECTION_STATUS,
  CONNECTION_STATUS_TO_HEALTH,
  CONNECTION_STATUS_TO_LABEL,
  CONNECTION_STATUS_TO_SHORT_LABEL,
  ConnectionStatus,
} from "./constants";

export {
  type ConnectionStatus as Type,
  CONNECTION_HEALTH as HEALTH,
  CONNECTION_STATUS as TYPE,
  CONNECTION_STATUS_TO_HEALTH as STATUS_TO_HEALTH,
  CONNECTION_STATUS_TO_LABEL as STATUS_TO_LABEL,
  CONNECTION_STATUS_TO_SHORT_LABEL as STATUS_TO_SHORT_LABEL,
  useConnectionStatus as use,
};
